from __future__ import annotations

GUILD_MATERIAL_BUY_PRICES = {
    "mat_moss_fiber": 6,
    "mat_cracked_stone": 6,
    "mat_small_crystal": 14,
    "mat_fire_stone": 18,
    "mat_scorched_iron": 22,
    "mat_lava_shard": 30,
    "mat_ravine_ash": 28,
    "mat_charred_iron": 32,
    "mat_flame_stone_refined": 45,
    "mat_ice_salt": 32,
    "mat_ice_saltcloth": 36,
    "mat_ice_wreck_plank": 38,
    "mat_ice_frostroot": 40,
    "mat_ice_blue_stone": 44,
    "mat_ice_frostiron": 52,
    "mat_ice_seal_dust": 58,
    "mat_ice_deep_core": 72,
    "mat_earth_moss_loam": 76,
    "mat_earth_rootfiber": 82,
    "mat_earth_spore_cap": 84,
    "mat_earth_quarry_stone": 90,
    "mat_earth_petrified_bark": 96,
    "mat_earth_leyline_shard": 108,
    "mat_earth_seal_clay": 116,
    "mat_earth_deep_core": 132,
    "mat_thunder_charge_sand": 140,
    "mat_thunder_copper_vein": 148,
    "mat_thunder_stormglass": 154,
    "mat_thunder_sky_stone": 164,
    "mat_thunder_conductor_rod": 172,
    "mat_thunder_cloud_essence": 188,
    "mat_thunder_seal_spark": 202,
    "mat_thunder_deep_core": 226,
    "mat_final_echo_ash": 240,
    "mat_final_frost_memory": 248,
    "mat_final_root_stone": 256,
    "mat_final_storm_glass": 264,
    "mat_final_void_shard": 280,
    "mat_final_seal_core": 310,
    "mat_final_demon_core": 340,
    "mat_final_deep_essence": 360,
}

REGION_LOCKED_REASONS = {
    "ice": "Ice Region unlocks after the Fire Seal route is complete.",
    "earth": "Earth Region unlocks after completing Ice Region quests.",
    "thunder": "Thunder Region unlocks after completing Earth Region quests.",
    "final": "Final Region requires all four enshrined elemental seals.",
}

def get_region_locked_reason(region_id: str) -> str:
    return REGION_LOCKED_REASONS.get(region_id, "This region is locked.")
